name: voice
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.3.0
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  shimmer: ^3.0.0
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.6
  carousel_slider: ^5.0.0
  logger: ^2.5.0
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.1.2
  skeletonizer: ^1.4.3
  flutter_chat_ui: ^1.6.15
  file_picker: ^10.1.2
  open_filex: ^4.7.0
  speech_to_text: ^7.0.0
  slide_to_act: ^2.0.2
  avatar_glow: ^3.0.1
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/animations/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/icons/domains/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
